#!/bin/sh
set -e

# from: https://docs.openshift.org/latest/creating_images/guidelines.html
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    export HOME="/home/${USER_NAME:-openshift}"
    echo "${USER_NAME:-openshift}:x:$(id -u):0:${USER_NAME:-openshift} user:${HOME}:/sbin/nologin" >> /etc/passwd
    # I would like that, but it results in:
    # chown: changing ownership of '/home/openshift': Operation not permitted
    # chown openshift ${HOME}
    mkdir -p ${HOME}/.ssh
    chmod 0700 ${HOME}/.ssh
  fi
fi

# below contents comes from:
# https://github.com/docker-library/php/blob/master/5.6/apache/docker-php-entrypoint

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
